import { NextResponse } from "next/server";

export const runtime = "nodejs";

/**
 * Inyecta credenciales de Supabase para el módulo estático de Créditos.
 *
 * Devuelve JavaScript que define:
 *   window.SB_URL
 *   window.SB_KEY
 *
 * Fuente:
 *   NEXT_PUBLIC_SUPABASE_URL
 *   NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
 * (Fallback para proyectos antiguos que usen NEXT_PUBLIC_SUPABASE_ANON_KEY)
 */
export async function GET() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  const key =
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
    "";

  const body = `// Auto-generated by Next.js (/creditos/env)\n\nwindow.SB_URL = window.SB_URL || ${JSON.stringify(url)};\nwindow.SB_KEY = window.SB_KEY || ${JSON.stringify(key)};\n`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Evita cache fuerte para que cambios de env se reflejen rápido.
      "Cache-Control": "no-store, max-age=0",
    },
  });
}
